#!/bin/sh
#set -x

#This script is used to export CM history hourly
#Update,collect racclimx-output from all was-nodes,at 20190619
#Update,Search was nodes automatically

CUR_HOUR=`date "+%d.%m.%YT%H" -d '-1 hour'`
START_MIN=00
END_MIN=59
TIME_NAME=`date "+%Y%m%d%H" -d '-1 hour'`
DATE_NAME=`date "+%Y%m%d" -d '-1 hour'`
TARGET_DIR=/home/omc/tool/Log_CM/Operation_Log
OMC_NAME=OMC2

if [ ! -d "${TARGET_DIR}/${DATE_NAME}" ]; then
  mkdir -p ${TARGET_DIR}/${DATE_NAME}
fi

racclimx.sh -op Diff_History -periodStart ${CUR_HOUR}:${START_MIN} -periodEnd ${CUR_HOUR}:${END_MIN} -fileName /tmp/${OMC_NAME}_CM_History.csv -v
if [ $? -ne 0 ];then
   echo "CM History Export Failed at ${CUR_HOUR},You can export data by useing : racclimx.sh -op Diff_History -periodStart${CUR_HOUR}:${START_MIN} -periodEnd ${CUR_HOUR}:${END_MIN} -fileName /t
mp/${OMC_NAME}_CM_History_${TIME_NAME}.csv -v" >> ${TARGET_DIR}/CM_Export.log
fi

for node in `/opt/cpf/sbin/netact_status.sh status service cmwas | grep : | awk -F ':' '{print $2}'`
do 
        scp -p omc@${node}:/tmp/${OMC_NAME}_CM_History.csv ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_Operation-${TIME_NAME}-${node}.csv
done

find ${TARGET_DIR}/${DATE_NAME}/ -mmin -10 -name '*vm*.csv' -exec cp {}  ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_Operation-${TIME_NAME}.csv \;
cat  ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_Operation-${TIME_NAME}.csv | grep -i 'NetAct' > ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_operation-${TIME_NAME}-tmp.csv
mv ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_operation-${TIME_NAME}-tmp.csv ${TARGET_DIR}/${DATE_NAME}/${OMC_NAME}_CM_Operation-${TIME_NAME}.csv

#gzip ${TARGET_DIR}/${OMC_NAME}_CM_History_${DATE_NAME}.csv
#find ${TARGET_DIR} -type d  -mtime +7 -exec rm -f {}  \;
find ${TARGET_DIR}/${DATE_NAME}/ -name '*vm*.csv' -exec rm -f {} \;
